service:
  name: bekk-idrett-api

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage,'dev'}
  region: ${file(../../config.yml):region}

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /hello
          method: GET
          cors: true

resources:
  Outputs:
    ApiGatewayRestApiId:
      Value:
        Ref: ApiGatewayRestApi
      Export:
        Name: ${opt:stage,'dev'}-ExtApiGatewayRestApiId

    ApiGatewayRestApiRootResourceId:
      Value:
        Fn::GetAtt: [ApiGatewayRestApi, RootResourceId]
      Export:
        Name: ${opt:stage,'dev'}-ExtApiGatewayRestApiRootResourceId
